version: '3'
services:
  chatgpt-telegram-bot:
    build:
      context: ../../../../../Desktop/chatgpt-telegram-bot-main
      dockerfile: Dockerfile
    volumes:
      - .:/app
    restart: unless-stopped
